### ISSUE TITLE
epo.syncDirectory command

### ISSUE THREAD

**Issue by eb90** [Kreloc/Posh-ePoAPI#1]
Hi @Kreloc 

Have you looked further to add function to synchorinze Domains and AD with the system tree using epo.syncDirectory command?

What I'm interested in about this funtion is to sync OUs let's say is named "Managed".
These OUs belongs to different sites and all of these sites belongs to a root OU called "Sites".
One example how the strucutre looks like:
Sites --> NEWYORK --> Computers --> Managed

Under the site specific OU, there are subOUs called Computers that contains "Legacy", "Managed" and "Other" OUs.
Sites --> NEWYORK --> Computers --> Legacy / Managed / Other

How I sync today:
I first need to sync the root OU called "Sites".
Then in the exclusions, I need to find all OUs called "Legacy" and Other", that will mean I'll only sync "Managed" OUs.

As you can see, this is a manual process and I want to automate this that the AD sync will only look for OUs called "Managed" and only sync them and not adding any exclusions.

**Comment by eb90** [comment]
Hi @Kreloc ,
I'm just curious, have you start looking into this?

**Comment by eb90** [comment]
Any updates? :) @Kreloc

**Comment by Kreloc** [comment]
Sorry, I ended up putting this module off to the side for a while and haven't come back to it. The  last time I looked into this, that command, epo.SyncDirectory, doesn't not actually change that information and the only way to do it is thru the McAfee epo web console.
